"""Scrollable help guide for the desktop app."""
from __future__ import annotations

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QDialog,
    QDialogButtonBox,
    QFrame,
    QHBoxLayout,
    QLabel,
    QPushButton,
    QScrollArea,
    QVBoxLayout,
    QWidget,
)

from .theme import _BORDER, _MUTED, _SURFACE2, _SKY, _SKY_DIM, _TEXT, _WARN, _SUCCESS, _DANGER


def _section(icon: str, title: str, body: str) -> QWidget:
    w = QWidget()
    lay = QVBoxLayout(w)
    lay.setContentsMargins(0, 0, 0, 0)
    lay.setSpacing(8)

    title_row = QHBoxLayout()
    title_row.setSpacing(10)
    title_row.setContentsMargins(0, 0, 0, 0)

    icon_lbl = QLabel(icon)
    icon_lbl.setStyleSheet(f"font-size: 16pt; background: transparent; color: {_SKY};")
    icon_lbl.setFixedWidth(28)
    icon_lbl.setAlignment(Qt.AlignmentFlag.AlignTop | Qt.AlignmentFlag.AlignHCenter)
    title_row.addWidget(icon_lbl)

    t = QLabel(title)
    t.setObjectName("HelpSectionTitle")
    t.setWordWrap(True)
    t.setAlignment(Qt.AlignmentFlag.AlignVCenter)
    title_row.addWidget(t, 1)

    lay.addLayout(title_row)

    b = QLabel(body)
    b.setObjectName("HelpSectionBody")
    b.setWordWrap(True)
    b.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByMouse)
    b.setContentsMargins(38, 0, 0, 0)
    lay.addWidget(b)

    return w


def _sep() -> QWidget:
    line = QWidget()
    line.setFixedHeight(1)
    line.setStyleSheet(f"background: {_BORDER};")
    return line


def _callout(text: str, color: str = _SKY_DIM, border: str = _SKY) -> QFrame:
    f = QFrame()
    f.setStyleSheet(
        f"QFrame {{ background-color: {color}; border: 1px solid {border}; border-radius: 8px; }}"
    )
    lay = QVBoxLayout(f)
    lay.setContentsMargins(14, 10, 14, 10)
    lbl = QLabel(text)
    lbl.setObjectName("HelpSectionBody")
    lbl.setWordWrap(True)
    lbl.setStyleSheet(f"color: {_TEXT}; border: none; background: transparent;")
    lay.addWidget(lbl)
    return f


def run_help_dialog(parent: QWidget) -> None:
    dlg = QDialog(parent)
    dlg.setWindowTitle("Help — SwiftTrade")
    dlg.setMinimumSize(520, 520)
    dlg.resize(580, 660)

    outer = QVBoxLayout(dlg)
    outer.setContentsMargins(24, 20, 24, 16)
    outer.setSpacing(14)

    head = QLabel("How SwiftTrade works")
    head.setObjectName("HelpDialogTitle")
    sub = QLabel(
        "SwiftTrade watches for AI-generated trading opportunities and, when you choose, "
        "automatically places trades on your Trading212 account."
    )
    sub.setObjectName("HelpDialogSubtitle")
    sub.setWordWrap(True)
    outer.addWidget(head)
    outer.addWidget(sub)

    outer.addWidget(
        _callout(
            "🔒  Your money is never touched unless you explicitly switch to Real trades mode. "
            "By default, everything runs in safe Demo mode.",
            color="rgba(34, 197, 94, 0.08)",
            border="rgba(34, 197, 94, 0.35)",
        )
    )

    scroll = QScrollArea()
    scroll.setWidgetResizable(True)
    scroll.setFrameShape(QFrame.Shape.NoFrame)
    scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)

    body = QWidget()
    content = QVBoxLayout(body)
    content.setContentsMargins(4, 4, 12, 8)
    content.setSpacing(20)

    sections = [
        (
            "🚀",
            "Getting started — 3 quick steps",
            "Step 1 — License key (optional)\n"
            "   If you are on the free plan, skip this entirely and go to Step 2.\n"
            "   If you have a Pro license, paste it here and click Check license.\n\n"
            "Step 2 — Connect to Trading212\n"
            "   Open the Trading212 app on your phone, go to Settings → API, and create a "
            "demo/practice key. Paste that key here and click Save demo keys.\n"
            "   Note: Start with a demo key — no real money is involved.\n\n"
            "Step 3 — Connect to SwiftTrade\n"
            "   Leave the server address at its default and click the green Connect button. "
            "When the dot at the top turns green, you are live and receiving signals.",
        ),
        (
            "📊",
            "What is a 'signal'?",
            "A signal is a recommendation generated by the SwiftTrade AI — it says "
            "something like 'Buy Apple stock now' or 'Sell Tesla'. The app receives "
            "these recommendations in real time and, depending on your settings, "
            "places the corresponding trade on Trading212 automatically.\n\n"
            "You can see every signal that arrives in the Signals tab, and a full "
            "history of what the app did in the What happened log on the right.",
        ),
        (
            "🎮",
            "Demo mode vs Real trades — what's the difference?",
            "Demo mode (default — safe)\n"
            "   Trades are placed on your Trading212 practice account. No real money is "
            "used. This is perfect for testing and understanding how the bot behaves "
            "before you risk anything.\n\n"
            "Real trades (requires Pro)\n"
            "   Trades are placed on your real Trading212 account using actual money. "
            "Only switch to this mode when you fully understand the bot's behavior "
            "and are ready to trade with real funds.",
        ),
        (
            "🗂️",
            "What each tab shows",
            "Get started — The setup wizard you are using now. Come back here any time "
            "to update your keys or reconnect.\n\n"
            "Live feed — A live view of which stock markets are currently open, what the "
            "bot is doing for each stock, and the most recent signals it has received.\n\n"
            "Signals — A full list of every signal that has arrived since you connected, "
            "newest at the top.\n\n"
            "What happened (right side) — A color-coded log of every action the app "
            "takes. Green = success, Yellow = warning, Red = something went wrong.",
        ),
        (
            "⚙️",
            "Settings explained",
            "Click the ⚙ gear icon in the top bar to open Settings.\n\n"
            "Order size — How many units of a stock to buy or sell per signal.\n"
            "Stop-loss — Automatically sell if a position loses more than X%. "
            "Set to 0 to disable.\n"
            "Max trades / day — Cap how many trades the bot places in a single day. "
            "0 means no limit.\n"
            "Cooldown — Wait at least this many seconds before trading the same stock "
            "again. Prevents over-trading.\n"
            "Confirm each order — Asks for your approval before placing any trade.\n"
            "LONG signals only — Only buy (never short-sell). Safer for most users.",
        ),
        (
            "🔧",
            "Something not working?",
            "• Check that you have an internet connection.\n"
            "• Make sure you saved your Trading212 demo key before clicking Connect.\n"
            "• Go to Get started → Troubleshooting → Open health check for a full "
            "diagnostic.\n"
            "• Try closing and reopening the app.\n"
            "• If nothing helps, visit swifttrade.io or open a support ticket from your "
            "dashboard.",
        ),
    ]

    for i, (icon, title, text) in enumerate(sections):
        if i > 0:
            content.addWidget(_sep())
        content.addWidget(_section(icon, title, text))

    content.addStretch(1)
    scroll.setWidget(body)
    outer.addWidget(scroll, 1)

    footer = QHBoxLayout()
    goto_setup = QPushButton("Go to Get started tab")
    goto_setup.setObjectName("SecondaryBtn")
    goto_setup.setCursor(Qt.CursorShape.PointingHandCursor)

    def _goto_setup() -> None:
        win = parent
        while win is not None:
            tabs = getattr(win, "tabs", None)
            if tabs is not None:
                tabs.setCurrentIndex(0)
                dlg.accept()
                return
            win = win.parent()  # type: ignore[assignment]

    goto_setup.clicked.connect(_goto_setup)  # type: ignore[arg-type]
    footer.addWidget(goto_setup)
    footer.addStretch(1)

    btns = QDialogButtonBox(QDialogButtonBox.StandardButton.Close)
    btns.button(QDialogButtonBox.StandardButton.Close).clicked.connect(dlg.accept)  # type: ignore[arg-type]
    footer.addWidget(btns)
    outer.addLayout(footer)

    dlg.setStyleSheet(
        f"""
        QDialog {{ background-color: #13131a; }}
        QLabel#HelpDialogTitle {{
            color: {_TEXT};
            font-size: 17pt;
            font-weight: 700;
            letter-spacing: -0.02em;
            background: transparent;
        }}
        QLabel#HelpDialogSubtitle {{
            color: {_MUTED};
            font-size: 9.5pt;
            line-height: 1.5;
            background: transparent;
        }}
        QLabel#HelpSectionTitle {{
            color: {_TEXT};
            font-size: 11pt;
            font-weight: 700;
            background: transparent;
        }}
        QLabel#HelpSectionBody {{
            color: {_MUTED};
            font-size: 9.5pt;
            line-height: 1.55;
            background: transparent;
        }}
        """
    )
    dlg.exec()
